// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBicXwggU7bjzHCT3tq89sL6A5EZWrao0E',
    appId: '1:398811507966:web:f8e10dfc90c81ac84349af',
    messagingSenderId: '398811507966',
    projectId: 'pharmacy-application-48ebd',
    authDomain: 'pharmacy-application-48ebd.firebaseapp.com',
    storageBucket: 'pharmacy-application-48ebd.appspot.com',
    measurementId: 'G-WTXSLZXSP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnoYVeLtWiSyalzNuBM3IngLow3dNSdpk',
    appId: '1:398811507966:android:b4016abe0aecb3f94349af',
    messagingSenderId: '398811507966',
    projectId: 'pharmacy-application-48ebd',
    storageBucket: 'pharmacy-application-48ebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYvmxzFv4BdfNe95O2IIHhSgpFT06pr34',
    appId: '1:398811507966:ios:f367c8edea88893b4349af',
    messagingSenderId: '398811507966',
    projectId: 'pharmacy-application-48ebd',
    storageBucket: 'pharmacy-application-48ebd.appspot.com',
    iosBundleId: 'com.example.pharmacyApp',
  );
}
